import numpy as np


#Constants

#Design constants

#Bootle properties
CST_BOOTTLE_2L_MASS = 
CST_BOOTTLE_2L_VOLUME = 0.002
CST_BOOTL_2L_DIAMETER = 0.1

CST_BOOTTLE_1dot5L_MASS = 0.1
CST_BOOTTLE_1dot5L_VOLUME = 0.0015
CST_BOOTL_1dot5L_DIAMETER = 0.1

#Rocket parts properties
CST_S1_BOOTLE_WEIGHT_DUAL = 0.106
CST_S1_BOOTLE_WEIGHT_SINGLE = 0.106
CST_S1_BOOTLE_COUNT = 1
CST_S2_BOOTLE_WEIGHT = 0.078
CST_BOOTLE_VOLUME = 0.002

#Rocket parts properties
CST_ROCKET_NOSE_CONE_MASS = 0.110
CST_ROCKET_FIN_WEIGHT = 0.050
CST_S1_NOOZLE_DIAMETER = 0.02
CST_COMPUTER_MASS = 0.130
CST_GOPRO_MASS = 0.194

#Physical constants
CST_WATER_DENSITY = 1000
CST_AIR_ATMOSPHERIC_DENSITY = 1.225
CST_ATMOSPHERIC_PRESSURE = 101325
CST_GRAVITY = 10
CST_HEAT_CAPACITY_RATIO = 1.4
CST_PERFECT_GAS_CONSTANT = 8.314 
CST_MASS_MOLAIRE_AIR = 0.029
CST_AIR_THROAT_VELOCITY = np.sqrt( CST_HEAT_CAPACITY_RATIO * (CST_PERFECT_GAS_CONSTANT/CST_MASS_MOLAIRE_AIR) * CST_AMBIANT_TEMPERATURE * ( 2/(CST_HEAT_CAPACITY_RATIO - 1)) )

#Default launc parameters

CST_LAUNCH_PRESSURE = 800000
CST_AMBIANT_TEMPERATURE = 20 + 273.15  #Kelvin

#Fly status
CST_THRUST_MODE_OFF = 0
CST_THRUST_MODE_WATER = 1
CST_THRUST_MODE_AIR_SHOCKED = 2
CST_THRUST_MODE_AIR_ISENTROPIC = 3
CST_SHOCK_FLOW_PRESSURE = CST_ATMOSPHERIC_PRESSURE * (2 / (CST_HEAT_CAPACITY_RATIO +1)) ** (- CST_HEAT_CAPACITY_RATIO/(CST_HEAT_CAPACITY_RATIO - 1))




#based on choked flow law



CST_S1_waterFlowRestriction = 0.7
CST_S1_airFlowRestriction = 0.36
CST_S2_waterFlowRestriction = 1
CST_S2_airFlowRestriction = 0.82